# Generated by Django 5.2.17 on 2026-10-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author', models.CharField(default='Dr. Dipesh Mahato', max_length=120)),
                ('category', models.CharField(default='Preventive Dentistry', max_length=100)),
                ('read_time', models.CharField(default='4 min read', max_length=50)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('sender_type', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('system', 'Clinical System')], default='patient', max_length=20)),
                ('sender_name', models.CharField(max_length=120)),
                ('doctor_id', models.CharField(default='dr-dipesh', max_length=50)),
                ('message', models.TextField()),
                ('attachment_url', models.TextField(blank=True, null=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('patient_phone', models.CharField(max_length=40)),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('document_type', models.CharField(choices=[('xray', 'Digital X-Ray / Radiograph'), ('cbct', 'CBCT 3D Scan'), ('panoramic', 'Panoramic OPG Radiograph'), ('prescription', 'Doctor Prescription'), ('report', 'Lab / Histopathology Report'), ('other', 'Other Medical Document')], default='xray', max_length=50)),
                ('file_url', models.TextField(help_text='File URL, Cloud Storage URI, or Data Payload')),
                ('file_name', models.CharField(blank=True, default='clinical_xray.png', max_length=255)),
                ('file_size_kb', models.IntegerField(default=0)),
                ('pain_level', models.IntegerField(default=0, help_text='Scale 0 (No pain) to 10 (Severe)')),
                ('urgency', models.CharField(choices=[('routine', 'Routine Assessment'), ('urgent', 'Urgent (Within 24 Hours)'), ('emergency', 'Emergency Dental Triage (Immediate)')], default='routine', max_length=30)),
                ('clinical_notes', models.TextField(blank=True)),
                ('assigned_doctor', models.CharField(default='Dr. Dipesh Mahato (Lead Dental Surgeon)', max_length=120)),
                ('doctor_review_notes', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clinical Document / X-Ray',
                'verbose_name_plural': 'Clinical Documents & X-Rays',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_interested', models.CharField(blank=True, default='General Consultation', max_length=120)),
                ('preferred_date', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact / Appointment Request',
                'verbose_name_plural': 'Contact / Appointment Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(default='General Dentistry', max_length=100)),
                ('icon', models.CharField(blank=True, default='medical_services', max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('price_range', models.CharField(blank=True, default='Standard clinical fee', max_length=100)),
                ('duration', models.CharField(blank=True, default='30-45 mins', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
